### ISSUE TITLE
Catch exception

### ISSUE THREAD

**Issue by jagadeesh1992** [darrenparkinson/SparkDotNet#10]
Hello,

I am using this SDK in one of my integrations. When I am trying to create a room with a Invalid access token the CreateRoomAsync methd Roonm object with null values instead of throwing a 401 error. I want to catch the response of the header of the web exception.

here is my code
    var token = "XXXXXXXXXXXXXXXXXXXXXX";
 var spark = new Spark(token);
        try
        {
            Room room = await spark.CreateRoomAsync(title: "XXXX", teamId:"XXXX");
            return (room);
        }
        catch(Exception ex)
        {
            throw ex;
        }

Thanks
Jagadeesh

**Comment by darrenparkinson** [comment]
Thanks for logging the issue. I've been wanting to add this,so now you've given me the motivation. I'm thinking of adding a new type of exception which you could catch like a SparkException or something which would include any errors/responses.  What do you think?

**Comment by jagadeesh1992** [comment]
Yes That sounds great. SparkException is a good idea to Include response header as well, Since response header has the tracking Id's which  will be used by CISCO for resolving issues.

**Comment by darrenparkinson** [comment]
How about throwing a `System.Net.Http.HttpRequestException` and adding details to the [Exception.Data property](https://msdn.microsoft.com/en-us/library/system.exception.data(v=vs.110).aspx), such as `Spark.ResponseCode`, `Spark.ReasonPhrase` and `Spark.Trackingid`?

Or do you think a separate SparkException would be better with custom properties?

**Comment by jagadeesh1992** [comment]
I think adding details to the exception.data.property works good.

**Comment by darrenparkinson** [comment]
@jagadeesh1992 thanks.  In the end I actually decided to go the SparkException route.  I've just pushed a [new branch](https://github.com/darrenparkinson/SparkDotNet/tree/Issue10) which you could try if you'd like.  Let me know if that fixes your issue.  I'll do some more testing, then merge those changes in.

**Comment by jagadeesh1992** [comment]
@darrenparkinson  Cool Thanks. I will try the new branch.

**Comment by darrenparkinson** [comment]
I'm hoping this is ok.  I've merged the changes and will close this issue.  Thanks for opening it.
