### ISSUE TITLE
Add sipAddress field to Room

### ISSUE THREAD

**Issue by jemagu** [darrenparkinson/SparkDotNet#14]
I'm missing the sipAddress field in the Room object. Is it possible to add it?

https://developer.webex.com/docs/api/v1/rooms/get-room-details

**Comment by darrenparkinson** [comment]
Hi, apologies for the slight delay.  I'm just looking at this now.  Have added sipAddress ok, just taking the opportunity to add a few other new fields that are missing.  Doing some testing now and will then push.

**Comment by darrenparkinson** [comment]
Have fixed in commit 2275adb04079fb273032bb9242b622f351b17ae8 -- thanks.

**Comment by jemagu** [comment]
Thanks a lot!
