### ISSUE TITLE
Is version 1.2.2 packaged correctly on nuget.org?

### ISSUE THREAD

**Issue by jemagu** [darrenparkinson/SparkDotNet#15]
I have upgraded from version 1.2.0 to 1.2.2 using nuget but now I get some stange errors. ```The type or namespace name 'SparkDotNet' could not be found```. When I examine the two .nupkg files they look very different and fuget.org reports no 'Assemblies' on 1.2.2. Is there a possibility that something went wrong when packaging the nupkg file for 1.2.2?

**Comment by darrenparkinson** [comment]
Hi, yes, I had some trouble packaging that up yesterday as they seem to have changed the nuget spec quite a lot.  Let me give that another go.  Apologies for that.

**Comment by darrenparkinson** [comment]
I've repackaged it as 1.2.4 and tried loading from nuget -- seems to be ok again now.  So sorry about that.  Could you give it a try now and let me know before I close this issue.  Thanks.

**Comment by jemagu** [comment]
Hi, version 1.2.4 is working fine for me, thank you for fixing it so fast.

**Comment by darrenparkinson** [comment]
Awesome, that's great news. Thank you.
