### ISSUE TITLE
Get List of Webinars using SparkDotNet

### ISSUE THREAD

**Issue by RaviRamDhali** [darrenparkinson/SparkDotNet#19]
The following code is working and we are getting results.
```c#
List<Room> rooms = Task.Run(async () => await spark.GetRoomsAsync(max: 10));
```
I see that WebEx API Document referrer to a [get] Events. However, Spark does not have a method GetEvents. My goal is to get a list of  Webinars. 

Can you guide me to the right Spark method ?

**Comment by darrenparkinson** [comment]
Hi.  The events api in this instance is more for compliance:

From the docs: https://developer.webex.com/docs/api/v1/events
> *Events are generated when actions take place within Webex Teams, such as when someone creates or deletes a message. Compliance Officers may use the Events API to retrieve events for all users within an organization. See the Compliance Guide for more information.*

There is a newly released API though for meetings which might have this capability: https://developer.webex.com/docs/api/v1/meetings

It is something we should look into adding for sure.

**Comment by darrenparkinson** [comment]
Hi @RaviRamDhali apologies for the delay, but wanted you to know that this capability has now been added by @dtibbe in commit 80fd87bb34ac9aaff0cc4a8532d4ea523f2e7f12 so you can now use `GetMeetingsAsync` for example -- let me know if you have any trouble.
