### ISSUE TITLE
how get token 

### ISSUE THREAD

**Issue by waledmet** [darrenparkinson/SparkDotNet#26]
i try to get token 
how can call 
https://webexapis.com/v1/authorize 
to get code and after this  get token

**Comment by dtibbe** [comment]
Basically you have to follow the flow as described in https://developer.webex.com/docs/integrations
How you access those URLs depends on you application..
Is it a web application? Is it a Windows application?
Or do you just want to test the API? Then you may use your personal token from the developer page..
