### ISSUE TITLE
static HttpClient

### ISSUE THREAD

**Issue by mszymczakowski** [darrenparkinson/SparkDotNet#4]
hello again! :)
I have an issue with HttpClient in `Spark.cs` being static

`private static HttpClient client = new HttpClient();`

it's because I'm using your library in different places of app and with different accessTokens, making it non-static resolves the problem.

**Comment by darrenparkinson** [comment]
Thanks for the PR.  Appreciate it.

**Comment by mszymczakowski** [comment]
No problem, glad I could help :)
